// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Clear stale localStorage credentials that might conflict with env vars
try {
  if (typeof localStorage !== 'undefined') {
    const storedUrl = localStorage.getItem('supabase_url');
    const storedKey = localStorage.getItem('supabase_anon_key');
    // If env vars are set and differ from localStorage, clear stale values
    if (SUPABASE_URL && storedUrl && storedUrl !== SUPABASE_URL) {
      localStorage.removeItem('supabase_url');
      localStorage.removeItem('supabase_anon_key');
    }
    if (SUPABASE_PUBLISHABLE_KEY && storedKey && storedKey !== SUPABASE_PUBLISHABLE_KEY) {
      localStorage.removeItem('supabase_url');
      localStorage.removeItem('supabase_anon_key');
    }
  }
} catch {}

const FALLBACK_URL = 'https://example.supabase.co';
const FALLBACK_KEY = 'public-anon-key';

// Always prioritize environment variables over localStorage
const effectiveUrl = SUPABASE_URL || FALLBACK_URL;
const effectiveKey = SUPABASE_PUBLISHABLE_KEY || FALLBACK_KEY;

const containsService = typeof effectiveKey === 'string' && effectiveKey.toLowerCase().includes('service');
const finalUrl = containsService ? FALLBACK_URL : effectiveUrl;
const finalKey = containsService ? FALLBACK_KEY : effectiveKey;
const useFallback = finalUrl === FALLBACK_URL || finalKey === FALLBACK_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(finalUrl, finalKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-application-name': 'rigel-business',
    },
  },
  db: {
    schema: 'public'
  }
});

export const hasSupabaseEnv = !useFallback;
