// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
let lsUrl: string | null = null;
let lsKey: string | null = null;
try {
  lsUrl = typeof localStorage !== 'undefined' ? localStorage.getItem('supabase_url') : null;
  lsKey = typeof localStorage !== 'undefined' ? localStorage.getItem('supabase_anon_key') : null;
} catch {}
const FALLBACK_URL = 'https://example.supabase.co';
const FALLBACK_KEY = 'public-anon-key';
const effectiveUrl = SUPABASE_URL || lsUrl || FALLBACK_URL;
const effectiveKey = SUPABASE_PUBLISHABLE_KEY || lsKey || FALLBACK_KEY;
const useFallback = effectiveUrl === FALLBACK_URL || effectiveKey === FALLBACK_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(effectiveUrl, effectiveKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'x-application-name': 'apex-accounts',
    },
  },
  db: {
    schema: 'public'
  }
});

export const hasSupabaseEnv = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) || !!(lsUrl && lsKey);